nelmio_api_doc:
    documentation:
        info:
            title: Test task
            description: REST API
            version: 1.0.0
        paths:
            /api/authentication_token:
                post:
                    tags:
                        - Пользователь(User)
                    summary: Авторизация - api_login_check
                    description: Авторизация
                    requestBody:
                        description: Логин и пароль
                        required: true
                        content:
                            application/json:
                                schema:
                                    properties:
                                        email:
                                            type: string
                                        password:
                                            type: string
                                            nullable: false
                                    required:
                                        - email
                                        - password
                    responses:
                        '200':
                            description: Успешная авторизация
                            content:
                                application/json:
                                    schema:
                                        type: object
                                        description: BEARER token
                                        properties:
                                            token:
                                                type: string
                                                description: BEARER token

                        '401':
                            description: Invalid credentials
                            content:
                                application/json:
                                    schema:
                                        type: object
                                        description: "Invalid credentials"
                                        properties:
                                            code:
                                                type: int
                                            message:
                                                type: string
    areas: # to filter documented areas
        path_patterns:
            - ^/api(?!/doc$) # Accepts routes under /api except /api/doc