vich_uploader:
    db_driver: orm
    metadata:
        type: attribute
    mappings:
        statement_attachment:
            uri_prefix: /attachments/statement
            upload_destination: '%kernel.project_dir%/public/attachments/statement'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true