services:
    web:
        image: nginx
        volumes:
            - ./.docker/conf/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - .:/var/www/
            - ./.docker/log/nginx:/var/log/nginx/
            - ./.docker/sert/:/etc/nginx/ssl/
        ports:
            - 80:80
        restart: always
        depends_on:
            - php
            - postgres
        networks:
            default:
                ipv4_address: 10.0.0.5
    php:
        build: .docker
        restart: always
        privileged: true
        volumes:
            - ./.docker/conf/php/php.ini:/usr/local/etc/php/conf.d/php.ini
            - .:/var/www/
            - /etc/timezone:/etc/timezone:ro
        networks:
            default:
                ipv4_address: 10.0.0.6

    postgres:
        image: postgres
        ports:
          - "5432:5432"
        environment:
            POSTGRES_DB: 'db'
            POSTGRES_USER: 'user'
            POSTGRES_PASSWORD: 'password'
        volumes:
            - ./.docker/postgres/db_data:/var/lib/postgresql/data
        restart: always
        networks:
            default:
                ipv4_address: 10.0.0.9

    pgadmin:
        image: dpage/pgadmin4
        environment:
            PGADMIN_DEFAULT_EMAIL: admin@postgres.com
            PGADMIN_DEFAULT_PASSWORD: password
        volumes:
            - ./.docker/postgres/pgadmin:/var/lib/pgadmin
        ports:
            - "8888:80"
            - "8282:80"
        depends_on:
            - postgres
        restart: always
        networks:
            default:
                ipv4_address: 10.0.0.10

    redis:
        image: redis
        ports:
            - "6379:6379"
        networks:
            default:
                ipv4_address: 10.0.0.3

networks:
    default:
        ipam:
            config:
                - subnet: 10.0.0.0/10
